-- Custom migration: Create GIN index on product.attributes for fast JSONB filtering
-- This cannot be generated by drizzle-kit, so it's a custom migration

-- Drop the btree index that drizzle creates (it won't work well for JSONB queries)
DROP INDEX IF EXISTS "product_attributes_gin_idx";

-- Create GIN index for efficient JSONB containment and key-value lookups
CREATE INDEX IF NOT EXISTS "product_attributes_gin_idx" ON "product" USING GIN ("attributes");

-- Add brandId index
CREATE INDEX IF NOT EXISTS "product_brandId_idx" ON "product" ("brand_id");
